//############# PROVEEDOR ######################################## 
# GET http://localhost:3000/api/proveedores


# GET http://localhost:3000/api/proveedores/2


# POST http://localhost:3000/api/proveedores
# Content-Type: application/json

# {
#   "Nombre": "Proveedor Nuevo",
#   "Contacto": "Juan Pérez",
#   "Estado": "Activo"
# }

# PUT http://localhost:3000/api/proveedores/2
# Content-Type: application/json

# {
#   "Nombre": "Proveedor Actualizado",
#   "Contacto": "María López",
#   "Estado": "Activo"
# }

# DELETE http://localhost:3000/api/proveedores/1



//############# Categoria

# put http://localhost:3000/api/categorias/1
# Content-Type: application/json

# {
#   "Nombre": "CAamara",
#   "Descripcion": "Graba y esas cosas"
# }
get http://localhost:3000/api/reportes/resumen-dash

get http://localhost:3000/api/categorias


put http://localhost:3000/api/productos/1
Content-Type: application/json

{
  
    "Nombre": "Holder pro",
    "Costo": 10.5,
    "PrecioVenta": 15.4,
    "CategoriaId": 2,
    "ProveedorId": 2
}